.\" Manpage for git-lock-remote
.TH man 1 "September 2017" "1.0" "git unlock-remote man page"
.SH NAME
git unlock-remote \- Unlock the push URL of a git remote
.SH SYNOPSIS
git unlock-remote <remote>
.SH DESCRIPTION
Clears the push URL of a remote (from no_push) to allow pushing to the default URL of that remote.
.SH SEE ALSO
git-lock-remote(1)
.SH BUGS
No known bugs.
.SH AUTHOR
John Hobbs <john@velvetcache.org>
