.\" Manpage for git-lock-remote
.TH man 1 "September 2017" "1.0" "git lock-remote man page"
.SH NAME
git lock-remote \- Lock the push URL of a git remote
.SH SYNOPSIS
git lock-remote <remote>
.SH DESCRIPTION
Sets the push URL of a remote to no_push, preventing accidental pushing to that remote.
.SH SEE ALSO
git-unlock-remote(1)
.SH BUGS
No known bugs.
.SH AUTHOR
John Hobbs <john@velvetcache.org>
